name: Plugin Request
description: Create a plugin request, where someone can pick it up and develop it!
labels: [up for grabs]
body:
  - type: markdown
    attributes:
      value: |
        Time to get creative!
  - type: input
    id: discord
    attributes:
      label: Discord Account
      description: Who on Discord is making this request? Not required.
      placeholder: username#0000
    validations:
      required: false
  - type: textarea
    id: plugin-description
    attributes:
      label: Plugin Description
      description: In basic terms, describe the plugin idea you have.
      placeholder: I think a plugin that does ... would be cool! Maybe if it could do ... too?
    validations:
      required: true
  - type: textarea
    id: detailed-plugin-description
    attributes:
      label: Go into more detail...
      description: If you'd like to, give us a bit more information on what you'd like this plugin to do and/or how you want it to work. Not required.
      placeholder: I think it should also do ..., ... and ... too. I'd like it to use ... instead of ... as I think that would be more user friendly.
    validations:
      required: false
  - type: checkboxes
    id: agreement-valid-request
    attributes:
      label: Request Agreement
      description: Have you made sure your plugin request is [possible and allowed](https://github.com/Aliucord/plugin-requests#submitting-a-request) ?
      options:
        - label: I have made sure my plugin is possible and abides by the rules!
          required: true
  - type: checkboxes
    id: agreement-check
    attributes:
      label: ​
      description: Have you checked to make sure your plugin was not already requested?
      options:
        - label: I did indeed check to make sure my plugin request is original!
          required: true